package AceptacionProducto;

import Modelos.AceptacionPc1;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author JC
 */
public class AceptacionProductoGUI2 extends javax.swing.JFrame {

    // Atributos 
    private Usuarios usr; // La instancia del usuario actual del sistema
    private Connection conexion; // Conexión a la BD
    private AceptacionPc1 apc1; // Se crea la instancia de la clase AceptacionPc1
    private AceptacionProductoServicio aps = new AceptacionProductoServicio(); // Se crea la instancia de la clase AceptacionProductoServicio

    /**
     * Creates new form AceptacionProducto
     */
    public AceptacionProductoGUI2() {
        try {
            inicializarVentanaYComponentes(); // Inicialización de componentes
        } catch (SQLException | ClassNotFoundException ex) {
            aps.manejarExcepcion("Surgio un error al abrir ACEPTACION PRODUCTO", ex); // Se muestra el mensaje de la excepción al usuario
        }
    }

    public AceptacionProductoGUI2(Usuarios usr) throws SQLException, ClassNotFoundException {
        try {
            inicializarVentanaYComponentes(); // Inicialización de componentes
            this.usr = usr; // Se define a el usuario actual del sistema
            this.apc1 = new AceptacionPc1(); // Se crea la instancia de AceptacionPc1
            
            aps.cargarNoRollos(conexion, cbxNoRollo); // Se obtienen los rollos previamente registrados en Inspección/Recibo 

            Date fechaActual = new Date(); // Se obtiene la fecha actual

            // Se definen datos por default en los componentes de texto y en el JDateChooser
            dchFechaLiberacion.setDate(fechaActual);
            txtInspeccionVisual.setText("OK");
            txtObservaciones.setText("INSPECCIÓN 100%");
        } catch (SQLException | ClassNotFoundException ex) {
            aps.manejarExcepcion("Surgio un error al abrir la ventana ACEPTACION PRODUCTO", ex); // Se muestra el mensaje de la excepción al usuario
        }
    }

    @Override
    public Image getIconImage() { // Método para obtener y cambiar el icono de la aplicación en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png")); // Se obtiene la imagen que se quiere poner como icono de la barra 
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJCIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAceptacionProducto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        lblFechaLiberacion = new javax.swing.JLabel();
        lblNoRollo = new javax.swing.JLabel();
        lblInspVisual = new javax.swing.JLabel();
        txtInspeccionVisual = new swing.TextField();
        txtObservaciones = new swing.TextField();
        lblObservaciones = new javax.swing.JLabel();
        dchFechaLiberacion = new com.toedter.calendar.JDateChooser();
        cbxNoRollo = new swing.ComboBoxSuggestion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        getContentPane().add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAceptacionProducto.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblAceptacionProducto.setForeground(new java.awt.Color(10, 110, 255));
        lblAceptacionProducto.setText("ACEPTACIÓN DEL PRODUCTO");
        jPanel1.add(lblAceptacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 50));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/continuar.png"))); // NOI18N
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 110, 50));

        lblFechaLiberacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaLiberacion.setForeground(new java.awt.Color(76, 109, 255));
        lblFechaLiberacion.setText("FECHA LIBERACIÓN:");
        jPanel1.add(lblFechaLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblNoRollo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoRollo.setForeground(new java.awt.Color(76, 109, 255));
        lblNoRollo.setText("NO. ROLLO:");
        jPanel1.add(lblNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblInspVisual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInspVisual.setForeground(new java.awt.Color(76, 109, 255));
        lblInspVisual.setText("INSP. VISUAL:");
        jPanel1.add(lblInspVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        jPanel1.add(txtInspeccionVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 200, -1));
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, -1));

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(76, 109, 255));
        lblObservaciones.setText("OBSERVACIONES:");
        jPanel1.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));
        jPanel1.add(dchFechaLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));

        jPanel1.add(cbxNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        cerrarVentana(); // Cierra la ventana actual
        aps.abrirAceptacionProductoGUI(usr); // Se vuelve a abrir la ventana actual
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Date fechaSeleccionada = dchFechaLiberacion.getDate(); // Se captura la fecha seleccionada en el componente JDateChooser
        String fechaLiberacion = aps.formatearFecha(fechaSeleccionada); // Se define el formato específico "dd/mm/aaaa" 

        // Se captura información requerida y se guarda en el objeto apc1
        apc1.setFecha(fechaLiberacion);
        apc1.setNoRollo(cbxNoRollo.getSelectedItem().toString());
        apc1.setInspVisual(txtInspeccionVisual.getText());
        apc1.setObservacion(txtObservaciones.getText());

        cerrarVentana(); // Se cierra la ventana actual
        aps.abrirRetencionDimensionalGUI(usr, apc1); // Se abre la ventana principal de Retención Dimensional 
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void inicializarVentanaYComponentes() throws SQLException, ClassNotFoundException {
        initComponents(); // Inicialización de Componentes
        this.setResizable(false); // Se define que no se puede redimensionar
        this.setLocationRelativeTo(null); // Indica que la ventana actual se abrirá al centro de la pantalla principal del sistema 
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Se deshabilita el boton de cerrar de la ventana
        this.conexion = Conexion.getInstance().getConnection(); // Inicialización de la conexión a la BD
    }

    private void cerrarVentana() {
        AceptacionProductoGUI2.this.dispose(); // Se liberan los recursos de la ventana actual
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AceptacionProductoGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AceptacionProductoGUI2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxNoRollo;
    private com.toedter.calendar.JDateChooser dchFechaLiberacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAceptacionProducto;
    private javax.swing.JLabel lblFechaLiberacion;
    private javax.swing.JLabel lblInspVisual;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNoRollo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JTextField txtInspeccionVisual;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
