/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AceptacionProducto;

import Modelos.AceptacionPc1;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JC
 */
public class AceptacionProducto extends javax.swing.JFrame {

    Usuarios usr;
    AceptacionPc1 apc1;
    AceptacionProductoServicio aps = new AceptacionProductoServicio();
    Connection conexion;
    /**
     * Creates new form AceptacionProducto
     */
    public AceptacionProducto() {
        initComponents();
        
    }

    public AceptacionProducto(Usuarios usr) throws SQLException, ClassNotFoundException {
        initComponents();
        this.conexion = Conexion.getInstance().getConnection(); // Obtener la conexión a la base de datos usando el Singleton
        this.usr = usr;
        this.setResizable(false); // Se define que no se puede redimensionar
        this.setDefaultCloseOperation(0); // Se deshabilita el boton de cerrar de la ventana
        this.apc1 = new AceptacionPc1();
        List<String> rollos = this.aps.obtenerNoRollos(conexion);
        // No. Rollos
        rollos.forEach((rollo) -> {
            cbxNoRollo.addItem(rollo);
        });
        
        datosPrueba();
    }

    @Override
    public Image getIconImage() { // Método para obtener y cambiar el icono de la aplicación en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png")); // Se obtiene la imagen que se quiere poner como icono de la barra 
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJCIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAceptacionProducto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        lblFechaLiberacion = new javax.swing.JLabel();
        lblNoRollo = new javax.swing.JLabel();
        lblInspVisual = new javax.swing.JLabel();
        txtInspeccionVisual = new swing.TextField();
        txtObservaciones = new swing.TextField();
        lblObservaciones = new javax.swing.JLabel();
        dchFechaLiberacion = new com.toedter.calendar.JDateChooser();
        cbxNoRollo = new swing.ComboBoxSuggestion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        getContentPane().add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAceptacionProducto.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblAceptacionProducto.setForeground(new java.awt.Color(10, 110, 255));
        lblAceptacionProducto.setText("ACEPTACIÓN DEL PRODUCTO");
        jPanel1.add(lblAceptacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 50));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/continuar.png"))); // NOI18N
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 110, 50));

        lblFechaLiberacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaLiberacion.setForeground(new java.awt.Color(76, 109, 255));
        lblFechaLiberacion.setText("FECHA LIBERACIÓN:");
        jPanel1.add(lblFechaLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblNoRollo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoRollo.setForeground(new java.awt.Color(76, 109, 255));
        lblNoRollo.setText("NO. ROLLO:");
        jPanel1.add(lblNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblInspVisual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInspVisual.setForeground(new java.awt.Color(76, 109, 255));
        lblInspVisual.setText("INSP. VISUAL:");
        jPanel1.add(lblInspVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        jPanel1.add(txtInspeccionVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 200, -1));
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, -1));

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(76, 109, 255));
        lblObservaciones.setText("OBSERVACIONES:");
        jPanel1.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));
        jPanel1.add(dchFechaLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));

        jPanel1.add(cbxNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        AceptacionProducto.this.dispose();
        try {
            AceptacionProductoGUI apGUI = new AceptacionProductoGUI(usr); // Se crea la instancia de la clase
            apGUI.setVisible(true); // Se muestra la ventana visible 
            apGUI.setLocationRelativeTo(null); // Se muestra al centro de la pantalla
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AceptacionProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Date selectedDate = dchFechaLiberacion.getDate(); // Obtén la fecha seleccionada
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Crea un objeto SimpleDateFormat para el formato deseado
        String fechaLiberacion = dateFormat.format(selectedDate); // Formatea la fecha y guárdala en una variable String
        
        apc1.setFecha(fechaLiberacion);
        apc1.setNoRollo(cbxNoRollo.getSelectedItem().toString());
        apc1.setInspVisual(txtInspeccionVisual.getText());
        apc1.setObservacion(txtObservaciones.getText());
        
        AceptacionProducto.this.dispose();
        try {
            RetencionDimensional rdGUI = new RetencionDimensional(usr, apc1);
            rdGUI.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AceptacionProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AceptacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AceptacionProducto().setVisible(true);
        });
    }
    
    public void datosPrueba(){
        // Establece la fecha por defecto
        java.util.Date defaultDate = new java.util.Date(); // Puedes cambiar esto a la fecha que desees
        dchFechaLiberacion.setDate(defaultDate);
        txtInspeccionVisual.setText("OK");
        txtObservaciones.setText("INSPECCIÓN 100%");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxNoRollo;
    private com.toedter.calendar.JDateChooser dchFechaLiberacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAceptacionProducto;
    private javax.swing.JLabel lblFechaLiberacion;
    private javax.swing.JLabel lblInspVisual;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNoRollo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JTextField txtInspeccionVisual;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
