/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AceptacionProducto;

import InspeccionRecibo.InspeccionReciboGUI;
import Modelos.AceptacionPc1;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JC
 */
public class AgregarVariable extends javax.swing.JFrame {

    Usuarios usr;
    Connection conexion;
    AceptacionPc1 apc1;
    AceptacionProductoServicio aps = new AceptacionProductoServicio();

    /**
     * Creates new form AgregarVariable
     *
     */

    public AgregarVariable() {
        initComponents();
        this.setDefaultCloseOperation(0); // Deshabilita el botón de cerrar de la ventana
        this.setResizable(false);
    }

    public AgregarVariable(Usuarios usr, AceptacionPc1 apc1) {
        initComponents();
        this.setDefaultCloseOperation(0); // Deshabilita el botón de cerrar de la ventana
        this.setResizable(false);
        this.apc1 = apc1;
        this.usr = usr;
        this.conexion = Conexion.getInstance().getConnection();
    }

    @Override
    public Image getIconImage() { // Método para obtener y cambiar el icono de la aplicación en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png")); // Se obtiene la imagen que se quiere poner como icono de la barra 
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarVariable = new javax.swing.JLabel();
        lblJCIcono = new javax.swing.JLabel();
        lblNuevaVariable = new javax.swing.JLabel();
        txtNuevaVariable = new swing.TextField();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));
        btnCancelar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarVariable.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblAgregarVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblAgregarVariable.setText("AGREGAR VARIABLE");
        jPanel1.add(lblAgregarVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblNuevaVariable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNuevaVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblNuevaVariable.setText("NUEVA VARIABLE:");
        jPanel1.add(lblNuevaVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jPanel1.add(txtNuevaVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 224, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 140, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        AgregarVariable.this.dispose(); // Se liberan los recursos de la interfaz
        try {
            RetencionDimensional apGUI = new RetencionDimensional(usr, apc1); // Se crea una instancia de la interfaz gráfica
            apGUI.setVisible(true); // Se hace visible la ventana
            apGUI.setLocationRelativeTo(null); // Indica que la ventana actual se abrirá al centro de la pantalla principal del sistema 
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RetencionDimensional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nuevaVariable = txtNuevaVariable.getText();
        try {
            aps.agregarNuevaVariable(conexion, nuevaVariable);
            JOptionPane.showMessageDialog(this, "NUEVA VARIABLE AGREGADA CORRECTAMENTE");
            AgregarVariable.this.dispose(); // Se liberan los recursos de la interfaz
        try {
            RetencionDimensional apGUI = new RetencionDimensional(usr, apc1); // Se crea una instancia de la interfaz gráfica
            apGUI.setVisible(true); // Se hace visible la ventana
            apGUI.setLocationRelativeTo(null); // Indica que la ventana actual se abrirá al centro de la pantalla principal del sistema 
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RetencionDimensional.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(AgregarVariable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVariable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVariable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVariable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVariable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgregarVariable().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarVariable;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNuevaVariable;
    private javax.swing.JTextField txtNuevaVariable;
    // End of variables declaration//GEN-END:variables
}
