package AceptacionProducto;

import Modelos.AceptacionPc1;
import Modelos.AceptacionPc2;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import Servicios.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AgregarVariableGUI extends javax.swing.JFrame {

    // Atributos
    private Usuarios usuario; // Usuario autenticado en la aplicación
    private Connection conexion; // Conexión a la Base de Datos
    private AceptacionPc1 aceptacionPc1; // Objeto para el manejo de información del componente
    private AceptacionPc2 aceptacionPc2; // Objeto para el manejo de información del componente
    private AceptacionProductoServicio aps; // Servicio para manejar la aceptación de productos

    public AgregarVariableGUI() {
        initComponents();
    }

    public AgregarVariableGUI(Usuarios usuario, AceptacionPc1 aceptacionPc1, AceptacionPc2 aceptacionPc2) {
        this.usuario = usuario;
        this.aceptacionPc1 = aceptacionPc1;
        this.aceptacionPc2 = aceptacionPc2;
        inicializarVentanaYComponentes();
    }

    @Override
    public Image getIconImage() { // Método para cambiar el icono en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarVariable = new javax.swing.JLabel();
        lblJCIcono = new javax.swing.JLabel();
        lblNuevaVariable = new javax.swing.JLabel();
        txtNuevaVariable = new swing.TextField();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));
        btnCancelar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarVariable.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblAgregarVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblAgregarVariable.setText("AGREGAR VARIABLE");
        jPanel1.add(lblAgregarVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblNuevaVariable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNuevaVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblNuevaVariable.setText("NUEVA VARIABLE:");
        jPanel1.add(lblNuevaVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jPanel1.add(txtNuevaVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 224, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 140, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cerrarVentana();
        aps.abrirRetencionDimensionalGUI(usuario, aceptacionPc1, aceptacionPc2);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nuevaVariable = txtNuevaVariable.getText();

        if (nuevaVariable.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo para agregar una nueva variable esta vacío");
        } else {
            try {
                agregarVariable(nuevaVariable);
            } catch (SQLException ex) {
                Utilidades.manejarExcepcion("ERROR al guardar la nueva Variable: ", ex);
                Logger.getLogger(AgregarVariableGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void inicializarVentanaYComponentes() {
        try {
            configurarVentana();
            inicializarAtributos();
        } catch (SQLException ex) {
            Utilidades.manejarExcepcion("ERROR al Abrir AgregarVariableGUI: ", ex);
            Logger.getLogger(AgregarVariableGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configurarVentana() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    private void inicializarAtributos() throws SQLException {
        this.conexion = Conexion.getInstance().conectar();
        this.aps = new AceptacionProductoServicio();
    }

    private void agregarVariable(String nuevaVariable) throws SQLException {
        aps.agregarNuevaVariable(conexion, nuevaVariable);
        JOptionPane.showMessageDialog(this, "NUEVA VARIABLE AGREGADA CORRECTAMENTE");
        cerrarVentana();
        aps.abrirRetencionDimensionalGUI(usuario, aceptacionPc1, aceptacionPc2);
    }

    private void cerrarVentana() {
        AgregarVariableGUI.this.dispose();
        Conexion.getInstance().desconectar(conexion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVariableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgregarVariableGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarVariable;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNuevaVariable;
    private javax.swing.JTextField txtNuevaVariable;
    // End of variables declaration//GEN-END:variables
}
