package AceptacionProducto;

import Modelos.AceptacionPc1;
import Modelos.AceptacionPc2;
import Modelos.AceptacionPc3;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import Servicios.Utilidades;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ModificarRDGUI extends javax.swing.JFrame {

    // Atributos
    private Usuarios usuario; // Usuario autenticado en la aplicación
    private Connection conexion; // Conexión a la Base de Datos
    private AceptacionPc1 aceptacionPc1; // Objeto para el manejo de información del componente
    private AceptacionPc2 aceptacionPc2; // Objeto para el manejo de información del componente
    private AceptacionPc3 aceptacionPc3; // Objeto para el manejo de información del componente
    private AceptacionPc3 aceptacionPc3Auxiliar; // Objeto auxiliar para el manejo de información del componente
    private AceptacionProductoServicio aps; // Servicio para manejar la aceptación de productos

    public ModificarRDGUI() {
        inicializarVentanaYComponentes();
    }

    public ModificarRDGUI(AceptacionPc3 aceptacionPc3, Usuarios usuario, AceptacionPc1 aceptacionPc1, AceptacionPc2 aceptacionPc2) {
        this.usuario = usuario;
        this.aceptacionPc1 = aceptacionPc1;
        this.aceptacionPc2 = aceptacionPc2;
        this.aceptacionPc3 = aceptacionPc3;
        this.aceptacionPc3Auxiliar = inicializarAceptacionPc3Auxiliar(aceptacionPc3);
        inicializarVentanaYComponentes();
    }

    @Override
    public Image getIconImage() { // Método para cambiar el icono en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJCIcono = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNoOperacion = new javax.swing.JLabel();
        lblVariable = new javax.swing.JLabel();
        lblEspecificacion = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtNoOperacion = new swing.TextField();
        txtVariable = new swing.TextField();
        txtEspecificacion = new swing.TextField();
        txtValor = new swing.TextField();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));
        btnCancelar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));
        dchFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblModificar.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(10, 110, 255));
        lblModificar.setText("MODIFICAR");
        jPanel1.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(10, 110, 255));
        lblFecha.setText("FECHA:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblNoOperacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoOperacion.setForeground(new java.awt.Color(10, 110, 255));
        lblNoOperacion.setText("No. OPERACIÓN:");
        jPanel1.add(lblNoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        lblVariable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblVariable.setText("VARIABLE:");
        jPanel1.add(lblVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lblEspecificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEspecificacion.setForeground(new java.awt.Color(10, 110, 255));
        lblEspecificacion.setText("ESPECIFICACIÓN:");
        jPanel1.add(lblEspecificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(10, 110, 255));
        lblValor.setText("VALOR:");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));
        jPanel1.add(txtNoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 210, -1));

        txtVariable.setEditable(false);
        jPanel1.add(txtVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 250, -1));

        txtEspecificacion.setEditable(false);
        jPanel1.add(txtEspecificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 170, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, -1));

        dchFecha.setEnabled(false);
        jPanel1.add(dchFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (aps.esValorValido(txtEspecificacion.getText(), txtValor.getText())) {
            actualizarDatos();
            modificarDatos();
        } else {
            txtValor.setText("");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cerrarVentana();
        aps.abrirRetencionDimensionalGUI(usuario, aceptacionPc1, aceptacionPc2);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void inicializarVentanaYComponentes() {
        try {
            configurarVentana();
            this.conexion = Conexion.getInstance().conectar();
            this.aps = new AceptacionProductoServicio();
            definirValoresPredeterminados();
        } catch (SQLException ex) {
            Utilidades.manejarExcepcion("Surgio un error al abrir ModificarRDGUI: ", ex);
            Logger.getLogger(ModificarRDGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configurarVentana() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    private void definirValoresPredeterminados() {
        Date fecha = aps.formatearFecha(aceptacionPc3.getFecha());
        dchFecha.setDate(fecha);

        txtValor.setText(aceptacionPc3.getValor());
        txtNoOperacion.setText(aceptacionPc3.getNoOp());
        txtVariable.setText(aceptacionPc3.getVariable());
        txtEspecificacion.setText(aceptacionPc3.getEspecificacion());
    }

    private AceptacionPc3 inicializarAceptacionPc3Auxiliar(AceptacionPc3 aceptacionPc3) {
        return new AceptacionPc3(
                aceptacionPc3.getId(),
                aceptacionPc3.getComponente(),
                aceptacionPc3.getNoOp(),
                aceptacionPc3.getNoTroquel(),
                aceptacionPc3.getFecha(),
                aceptacionPc3.getVariable(),
                aceptacionPc3.getEspecificacion(),
                aceptacionPc3.getValor(),
                0
        );
    }

    private void actualizarDatos() {
        Date fechaSeleccionada = dchFecha.getDate();
        String fecha = aps.formatearFecha(fechaSeleccionada);

        String valor = txtValor.getText();
        String noOp = txtNoOperacion.getText();
        String variable = txtVariable.getText();
        String especificacion = txtEspecificacion.getText();

        if (!fecha.isEmpty() && !noOp.isEmpty() && !variable.isEmpty() && !especificacion.isEmpty() && !valor.isEmpty()) {
            aceptacionPc3.setFecha(fecha);
            aceptacionPc3.setNoOp(noOp);
            aceptacionPc3.setVariable(variable);
            aceptacionPc3.setEspecificacion(especificacion);
            aceptacionPc3.setValor(valor);
        } else {
            JOptionPane.showMessageDialog(this, "HAY CAMPOS INCOMPLETOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void modificarDatos() {
        try {
            aps.modificarAceptacionPc3(conexion, aceptacionPc3, aceptacionPc3Auxiliar);
            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS.");
            cerrarVentana();
            aps.abrirRetencionDimensionalGUI(usuario, aceptacionPc1, aceptacionPc2);
        } catch (SQLException ex) {
            Utilidades.manejarExcepcion("ERROR al guardar el registro: ", ex);
            Logger.getLogger(ModificarRDGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cerrarVentana() {
        ModificarRDGUI.this.dispose();
        Conexion.getInstance().desconectar(conexion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarRDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarRDGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dchFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEspecificacion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNoOperacion;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVariable;
    private javax.swing.JTextField txtEspecificacion;
    private javax.swing.JTextField txtNoOperacion;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVariable;
    // End of variables declaration//GEN-END:variables
}
