package AceptacionProducto;

import Modelos.AceptacionPc1;
import Modelos.AceptacionPc2;
import Modelos.DatosFilaRD;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import Servicios.Utilidades;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ModificarAPGUI extends javax.swing.JFrame {

    private Usuarios usr;
    private Connection conexion;
    private DatosFilaRD datosFila = new DatosFilaRD();
    private AceptacionProductoServicio aps = new AceptacionProductoServicio();

    public ModificarAPGUI() {
        try {
            inicializarVentanaYComponentes();
        } catch (SQLException | ClassNotFoundException ex) {
            Utilidades.manejarExcepcion("Error en ModificarAPGUI: ", ex);
            Logger.getLogger(ModificarAPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ModificarAPGUI(Usuarios usr) throws SQLException, ClassNotFoundException {
        this.usr = usr;
        inicializarVentanaYComponentes();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNoRollo = new swing.TextField();
        txtInspVisual = new swing.TextField();
        txtObservaciones = new swing.TextField();
        txtNoOrden = new swing.TextField();
        txtTamLote = new swing.TextField();
        txtTamMta = new swing.TextField();
        txtInsp = new swing.TextField();
        txtTurno = new swing.TextField();
        txtDisp = new swing.TextField();
        btnCerrar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));
        cbxComponente = new swing.ComboBoxSuggestion();
        cbxFecha = new swing.ComboBoxSuggestion();
        lblComponente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNoRollo = new javax.swing.JLabel();
        lblInspVisual = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        lblNoOrden = new javax.swing.JLabel();
        lblTamLote = new javax.swing.JLabel();
        lblTamMta = new javax.swing.JLabel();
        lblInsp = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblDisp = new javax.swing.JLabel();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(10, 110, 255));
        lblTitulo.setText("MODIFICAR DATOS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 72));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));
        jPanel1.add(txtNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 210, -1));
        jPanel1.add(txtInspVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, -1));
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 160, -1));
        jPanel1.add(txtNoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 150, -1));
        jPanel1.add(txtTamLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 150, -1));
        jPanel1.add(txtTamMta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 150, -1));
        jPanel1.add(txtInsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 180, -1));
        jPanel1.add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 180, -1));
        jPanel1.add(txtDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 180, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, 40));

        jPanel1.add(cbxComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 220, 30));

        jPanel1.add(cbxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 220, 30));

        lblComponente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblComponente.setForeground(new java.awt.Color(10, 110, 255));
        lblComponente.setText("COMPONENTE:");
        jPanel1.add(lblComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(10, 110, 255));
        lblFecha.setText("FECHA:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        lblNoRollo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoRollo.setForeground(new java.awt.Color(10, 110, 255));
        lblNoRollo.setText("NO. ROLLO:");
        jPanel1.add(lblNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblInspVisual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInspVisual.setForeground(new java.awt.Color(10, 110, 255));
        lblInspVisual.setText("INSP. VISUAL:");
        jPanel1.add(lblInspVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(10, 110, 255));
        lblObservaciones.setText("OBSERVACIONES:");
        lblObservaciones.setToolTipText("");
        jPanel1.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblNoOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoOrden.setForeground(new java.awt.Color(10, 110, 255));
        lblNoOrden.setText("NO. ORDEN:");
        jPanel1.add(lblNoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        lblTamLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTamLote.setForeground(new java.awt.Color(10, 110, 255));
        lblTamLote.setText("TAM. LOTE:");
        jPanel1.add(lblTamLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        lblTamMta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTamMta.setForeground(new java.awt.Color(10, 110, 255));
        lblTamMta.setText("TAM. MTA:");
        jPanel1.add(lblTamMta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        lblInsp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInsp.setForeground(new java.awt.Color(10, 110, 255));
        lblInsp.setText("INSP:");
        jPanel1.add(lblInsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(10, 110, 255));
        lblTurno.setText("TURNO:");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        lblDisp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDisp.setForeground(new java.awt.Color(10, 110, 255));
        lblDisp.setText("DISP:");
        jPanel1.add(lblDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        AceptacionPc1 apc1 = new AceptacionPc1();
        AceptacionPc2 apc2 = new AceptacionPc2();

        apc1.setComponente(cbxComponente.getSelectedItem().toString());
        apc1.setFecha(cbxFecha.getSelectedItem().toString());
        apc1.setNoRollo(txtNoRollo.getText());
        apc1.setInspVisual(txtInspVisual.getText());
        apc1.setObservacion(txtObservaciones.getText());

        apc2.setComponente(cbxComponente.getSelectedItem().toString());
        apc2.setFecha(cbxFecha.getSelectedItem().toString());

        txtNoOrden.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                String newText = txtNoOrden.getText();
                List<String> newNoOrdenList = Arrays.asList(newText.split("\\s*,\\s*"));
                datosFila.setNoOrden(new ArrayList<>(newNoOrdenList));
            }
        });

        try {
            aps.modificarInfoRD(conexion, apc1, datosFila);
        } catch (SQLException ex) {
            Utilidades.manejarExcepcion("Error al actualizar la información: ", ex);
            Logger.getLogger(ModificarAPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        cerrarVentana();
        JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS CORRECTAMENTE");
        aps.abrirAceptacionProductoGUI(usr);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrarVentana();
        aps.abrirAceptacionProductoGUI(usr);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void inicializarVentanaYComponentes() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.conexion = Conexion.getInstance().getConnection();
        aps.obtenerComponetes(conexion).forEach(cbxComponente::addItem);

        cbxComponente.addActionListener((ActionEvent ae) -> {
            try {
                cbxFecha.removeAllItems();
                String componenteSeleccionado = cbxComponente.getSelectedItem().toString();
                List<String> fechasRD = aps.obtenerFechasRD(conexion, componenteSeleccionado);
                fechasRD.forEach(cbxFecha::addItem);
            } catch (SQLException ex) {
                Utilidades.manejarExcepcion("Error al recuperar la información: ", ex);
                Logger.getLogger(ModificarAPGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        cbxFecha.addActionListener((ActionEvent ae) -> {
            try {
                String componenteSeleccionado = cbxComponente.getSelectedItem().toString();
                datosFila = aps.obtenerInfoRD(conexion, componenteSeleccionado, cbxFecha.getSelectedItem().toString());

                txtNoRollo.setText(datosFila.getNoRollo());
                txtInspVisual.setText(datosFila.getInspVisual());
                txtObservaciones.setText(datosFila.getObservaciones());

                txtNoOrden.setText(String.join(", ", datosFila.getNoOrden()));
                txtTamLote.setText(datosFila.getTamLote());
                txtTamMta.setText(datosFila.getTamMta());

                txtInsp.setText(datosFila.getInsp());
                txtTurno.setText(datosFila.getTurno());
                txtDisp.setText(datosFila.getDisp());
            } catch (SQLException ex) {
                Utilidades.manejarExcepcion("Error al recuperar la información: ", ex);
                Logger.getLogger(ModificarAPGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private void cerrarVentana() {
        ModificarAPGUI.this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarAPGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxComponente;
    private javax.swing.JComboBox<String> cbxFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComponente;
    private javax.swing.JLabel lblDisp;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblInsp;
    private javax.swing.JLabel lblInspVisual;
    private javax.swing.JLabel lblNoOrden;
    private javax.swing.JLabel lblNoRollo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTamLote;
    private javax.swing.JLabel lblTamMta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txtDisp;
    private javax.swing.JTextField txtInsp;
    private javax.swing.JTextField txtInspVisual;
    private javax.swing.JTextField txtNoOrden;
    private javax.swing.JTextField txtNoRollo;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtTamLote;
    private javax.swing.JTextField txtTamMta;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
