/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AceptacionProducto;

import InspeccionRecibo.ModificarIr;
import Modelos.AceptacionPc3;
import Modelos.Usuarios;
import Servicios.AceptacionProductoServicio;
import Servicios.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JC
 */
public class ModificarRD extends javax.swing.JFrame {

    Usuarios usr;
    Connection conexion;
    AceptacionProductoServicio aps = new AceptacionProductoServicio();
    AceptacionPc3 apc3, apc32;

    /**
     * Creates new form ModificarRD
     */
    public ModificarRD() {
        initComponents();
    }

    public ModificarRD(AceptacionPc3 apc3, Usuarios usr) {
        initComponents();
        this.conexion = Conexion.getInstance().getConnection(); // Obtener la conexión a la base de datos usando el Singleton
        this.usr = usr;
        this.apc3 = apc3;
        this.apc32 = new AceptacionPc3(this.apc3.getId(), this.apc3.getComponente(), this.apc3.getNoOp(), this.apc3.getFecha(), this.apc3.getVariable(), this.apc3.getEspecificacion(), this.apc3.getValor());

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Crear un objeto SimpleDateFormat para analizar la cadena de fecha
            Date fecha = dateFormat.parse(this.apc3.getFecha()); // Parsear la cadena de fecha en un objeto Date
            dchFecha.setDate(fecha); // Establecer la fecha en el JDateChooser
        } catch (ParseException e) {
        }
        txtNoOperacion.setText(apc3.getNoOp());
        txtVariable.setText(apc3.getVariable());
        txtEspecificacion.setText(apc3.getEspecificacion());
        txtValor.setText(apc3.getValor());
    }

    @Override
    public Image getIconImage() { // Método para obtener y cambiar el icono de la aplicación en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png")); // Se obtiene la imagen que se quiere poner como icono de la barra 
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJCIcono = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNoOperacion = new javax.swing.JLabel();
        lblVariable = new javax.swing.JLabel();
        lblEspecificacion = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtNoOperacion = new swing.TextField();
        txtVariable = new swing.TextField();
        txtEspecificacion = new swing.TextField();
        txtValor = new swing.TextField();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));
        btnCancelar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));
        dchFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblModificar.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(10, 110, 255));
        lblModificar.setText("MODIFICAR");
        jPanel1.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(10, 110, 255));
        lblFecha.setText("FECHA:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblNoOperacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoOperacion.setForeground(new java.awt.Color(10, 110, 255));
        lblNoOperacion.setText("No. OPERACIÓN:");
        jPanel1.add(lblNoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        lblVariable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVariable.setForeground(new java.awt.Color(10, 110, 255));
        lblVariable.setText("VARIABLE:");
        jPanel1.add(lblVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lblEspecificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEspecificacion.setForeground(new java.awt.Color(10, 110, 255));
        lblEspecificacion.setText("ESPECIFICACIÓN:");
        jPanel1.add(lblEspecificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(10, 110, 255));
        lblValor.setText("VALOR:");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));
        jPanel1.add(txtNoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 210, -1));

        txtVariable.setEditable(false);
        jPanel1.add(txtVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 250, -1));

        txtEspecificacion.setEditable(false);
        txtEspecificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecificacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtEspecificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 170, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, -1));
        jPanel1.add(dchFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecificacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Obtén la fecha seleccionada
        Date selectedDate = dchFecha.getDate();
        // Crea un objeto SimpleDateFormat para el formato deseado
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        // Se almacenan los datos capturados en las variable
        String fecha = dateFormat.format(selectedDate); // Formatea la fecha y guárdala en una variable String
        String noOp = txtNoOperacion.getText();
        String variable = txtVariable.getText();
        String especificacion = txtEspecificacion.getText();
        String valor = txtValor.getText();

        // Si los campos no estan vacios
        if (!fecha.isEmpty() || !noOp.isEmpty() || !variable.isEmpty() || !especificacion.isEmpty() || !valor.isEmpty()) {
            this.apc3.setFecha(fecha);
            this.apc3.setNoOp(noOp);
            this.apc3.setVariable(variable);
            this.apc3.setEspecificacion(especificacion);
            this.apc3.setValor(valor);
            modificarDatos(); // Se realiza la modificación
        } else {
            JOptionPane.showMessageDialog(this, "HAY CAMPOS INCOMPLETOS.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ModificarRD.this.dispose(); // Se liberan los recursos de la interfaz
        try {
            RetencionDimensional apGUI = new RetencionDimensional(usr); // Se crea una instancia de la interfaz gráfica
            apGUI.setVisible(true); // Se hace visible la ventana
            apGUI.setLocationRelativeTo(null); // Indica que la ventana actual se abrirá al centro de la pantalla principal del sistema 
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RetencionDimensional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarRD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dchFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEspecificacion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNoOperacion;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVariable;
    private javax.swing.JTextField txtEspecificacion;
    private javax.swing.JTextField txtNoOperacion;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVariable;
    // End of variables declaration//GEN-END:variables

    private void modificarDatos() {
        try {
            this.aps.modificar(conexion, this.apc3, this.apc32);
            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS.");

            ModificarRD.this.dispose(); // Se liberan los recursos de la interfaz
            try {
                RetencionDimensional apGUI = new RetencionDimensional(usr); // Se crea una instancia de la interfaz gráfica
                apGUI.setVisible(true); // Se hace visible la ventana
                apGUI.setLocationRelativeTo(null); // Indica que la ventana actual se abrirá al centro de la pantalla principal del sistema 
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(RetencionDimensional.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificarIr.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }
    }
}
