package Documentos;

import Modelos.ProcedimientosM;
import Modelos.ProcesosM;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.ControlDocumentacionServicio;
import Servicios.Utilidades;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ModificarInfoGUI extends javax.swing.JFrame {

    // Atributos
    private Usuarios usuario; // Usuario autenticado en la aplicación
    private ProcesosM proceso; // Gestiona la información del proceso
    private Connection conexion; // Conexión a la Base de Datos
    private String tipoOperacion; // Define si la operación corresponde a un documento, proceso o procedimiento
    private ProcedimientosM procedimiento; // Manejar la información del procedimiento
    private ControlDocumentacionServicio cds; // Servicios y Utilidades

    public ModificarInfoGUI() {
        initComponents();
    }

    public ModificarInfoGUI(Usuarios usuario, ProcedimientosM procedimiento) {
        this.usuario = usuario;
        this.procedimiento = procedimiento;
        this.tipoOperacion = "modificar";
        inicializarVentanaYComponentes();
    }

    public ModificarInfoGUI(Usuarios usuario, ProcesosM proceso) {
        this.usuario = usuario;
        this.proceso = proceso;
        this.procedimiento = new ProcedimientosM();
        this.tipoOperacion = "agregar";
        inicializarVentanaYComponentes();
    }

    @Override
    public Image getIconImage() { // Método para cambiar el icono en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJCIcono = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblRevision = new javax.swing.JLabel();
        lblProcedimiento = new javax.swing.JLabel();
        lblDueñoProceso = new javax.swing.JLabel();
        txtNo = new swing.TextField();
        txtCodigo = new swing.TextField();
        txtRevision = new swing.TextField();
        txtProcedimiento = new swing.TextField();
        txtDueñoProceso = new swing.TextField();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new swing.Button(new Color(255, 76, 76),new Color(255, 50, 50));
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblNo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNo.setForeground(new java.awt.Color(76, 109, 255));
        lblNo.setText("NO:");
        jPanel1.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(76, 109, 255));
        lblCodigo.setText("CÓDIGO:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        lblRevision.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblRevision.setForeground(new java.awt.Color(76, 109, 255));
        lblRevision.setText("REVISIÓN:");
        jPanel1.add(lblRevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        lblProcedimiento.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblProcedimiento.setForeground(new java.awt.Color(76, 109, 255));
        lblProcedimiento.setText("PROCEDIMIENTO:");
        jPanel1.add(lblProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        lblDueñoProceso.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblDueñoProceso.setForeground(new java.awt.Color(76, 109, 255));
        lblDueñoProceso.setText("DUEÑO DE PROCESO:");
        jPanel1.add(lblDueñoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 350, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 310, -1));
        jPanel1.add(txtRevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 300, -1));
        jPanel1.add(txtProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 250, -1));
        jPanel1.add(txtDueñoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 230, -1));

        lblTitulo.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(10, 110, 255));
        lblTitulo.setText("MODIFICAR INFORMACIÓN DEL PROCEDIMIENTO:");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 640, 50));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCerrar.setText("CANCELAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, 50));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int idProceso = procedimiento.getIdp() == 0 ? proceso.getId() : procedimiento.getIdp();
        cerrarVentana();
        cds.abrirDocumentacionGUI(usuario, idProceso);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (tipoOperacion.equals("modificar")) {
            actualizarInformacion();
            cds.guardarCambiosProcedimiento(conexion, procedimiento);
            cerrarVentana();
            JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS CORRECTAMENTE");
            cds.abrirDocumentacionGUI(usuario, procedimiento.getIdp());
        } else {
            agregarInformacion();
            cds.agregarProcedimiento(conexion, procedimiento);
            cerrarVentana();
            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void inicializarVentanaYComponentes() {
        try {
            configurarVentana();
            inicializarAtributos();
            definirTitulo();
        } catch (SQLException ex) {
            Utilidades.manejarExcepcion("ERROR al Abrir ModificarInfoGUI: ", ex);
            Logger.getLogger(ModificarInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configurarVentana() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    private void inicializarAtributos() throws SQLException {
        this.conexion = Conexion.getInstance().conectar();
        this.cds = new ControlDocumentacionServicio();
    }

    private void definirTitulo() {
        if (tipoOperacion.equals("modificar")) {
            lblTitulo.setText("MODIFICAR INFORMACIÓN DEL PROCEDIMIENTO: ");
            inicializarCampos();
        } else {
            lblTitulo.setText("AGREGAR PROCEDIMIENTO: ");
        }
    }

    private void inicializarCampos() {
        txtNo.setText(procedimiento.getNo());
        txtCodigo.setText(procedimiento.getCodigo());
        txtRevision.setText(procedimiento.getRevision());
        txtProcedimiento.setText(procedimiento.getProcedimiento());
        txtDueñoProceso.setText(procedimiento.getEncargado());
    }

    private void cerrarVentana() {
        ModificarInfoGUI.this.dispose();
        Conexion.getInstance().desconectar(conexion);
    }

    private void actualizarInformacion() {
        procedimiento.setNo(txtNo.getText());
        procedimiento.setCodigo(txtCodigo.getText());
        procedimiento.setRevision(txtRevision.getText());
        procedimiento.setProcedimiento(txtProcedimiento.getText());
        procedimiento.setEncargado(txtDueñoProceso.getText());
    }

    private void agregarInformacion() {
        procedimiento.setIdp(proceso.getId());
        procedimiento.setNo(txtNo.getText());
        procedimiento.setCodigo(txtCodigo.getText());
        procedimiento.setRevision(txtRevision.getText());
        procedimiento.setProceso(proceso.getProceso());
        procedimiento.setProcedimiento(txtProcedimiento.getText());
        procedimiento.setEncargado(txtDueñoProceso.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarInfoGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDueñoProceso;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblProcedimiento;
    private javax.swing.JLabel lblRevision;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDueñoProceso;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtProcedimiento;
    private javax.swing.JTextField txtRevision;
    // End of variables declaration//GEN-END:variables
}
