package BotonesAccion;

import java.awt.event.ActionEvent;

public class PanelAction extends javax.swing.JPanel {

    public PanelAction(boolean showEdit, boolean showDelete, boolean showView, boolean showOpenRecords, boolean showAccept, boolean showReject) {
        initComponents();

        // Solo mostramos los botones que son necesarios
        btnEditar.setVisible(showEdit);
        btnEliminar.setVisible(showDelete);
        btnVer.setVisible(showView);
        btnAbrirRegistros.setVisible(showOpenRecords);
        btnAceptar.setVisible(showAccept);
        btnRechazar.setVisible(showReject);
    }

    public void initEvent(TableActionEvent event, int row) {
        // Asignar eventos a los botones
        btnEditar.addActionListener((ActionEvent ae) -> {
            event.onEdit(row);
        });

        btnEliminar.addActionListener((ActionEvent ae) -> {
            event.onDelete(row);
        });

        btnVer.addActionListener((ActionEvent ae) -> {
            event.onView(row);
        });

        btnAbrirRegistros.addActionListener((ActionEvent ae) -> {
            event.onOpenRecords(row);
        });

        btnAceptar.addActionListener((ActionEvent ae) -> {
            event.onAccept(row);
        });

        btnRechazar.addActionListener((ActionEvent ae) -> {
            event.onReject(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVer = new BotonesAccion.ActionButton();
        btnEditar = new BotonesAccion.ActionButton();
        btnEliminar = new BotonesAccion.ActionButton();
        btnAbrirRegistros = new BotonesAccion.ActionButton();
        btnRechazar = new BotonesAccion.ActionButton();
        btnAceptar = new BotonesAccion.ActionButton();

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonesAccion/view.png"))); // NOI18N

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonesAccion/edit.png"))); // NOI18N

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonesAccion/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("");

        btnAbrirRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/antecedentesfamilia.png"))); // NOI18N

        btnRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/ok2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAbrirRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonesAccion.ActionButton btnAbrirRegistros;
    private BotonesAccion.ActionButton btnAceptar;
    private BotonesAccion.ActionButton btnEditar;
    private BotonesAccion.ActionButton btnEliminar;
    private BotonesAccion.ActionButton btnRechazar;
    private BotonesAccion.ActionButton btnVer;
    // End of variables declaration//GEN-END:variables
}
