/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jc.sgc;

import AceptacionProducto.AceptacionProductoGUI;
import InspeccionRecibo.InspeccionReciboGUI;
import Modelos.Usuarios;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author JC
 */
public class Menu extends javax.swing.JFrame {

    Usuarios usr; // Instancia de la clase Usuarios

    /**
     * Creates new form Menu
     */
    public Menu() {
        inicializarVentana();
    }

    public Menu(Usuarios usr) {
        inicializarVentana();
        this.usr = usr; // Se define el Usuario
        
        // Se habilitan/deshabilitan los botones del menú
        btnInspeccionRecibo.setEnabled(true);
        btnAceptacionProducto.setEnabled(true);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        //Color de los Botones
        setColores(btnInspeccionRecibo);
        setColores(btnAceptacionProducto);
    }
    
    public final void setColores(JButton btn) {
        btn.setBackground(new Color(0, 139, 255));
        btn.setForeground(new Color(250, 250, 250));
    }

    public final void inicializarVentana() {
        initComponents(); //Inicialización de los componentes de la interfaz
        this.setResizable(false); // Se indica que no se puede redimensionar la ventana 
        this.setDefaultCloseOperation(0); // Se deshabilita el boton de cerrar de la ventana  
        setLocationRelativeTo(null); // Muestra la ventana al centro de la pantalla
    }

    @Override
    public Image getIconImage() { // Método para obtener y cambiar el icono de la aplicación en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png")); // Se obtiene la imagen que se quiere poner como icono de la barra 
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMenu = new javax.swing.JPanel();
        lblJCIcono = new javax.swing.JLabel();
        btnLogOut = new swing.Button(new Color(255, 202, 102), new Color(255, 166, 0));
        btnInspeccionRecibo = new swing.Button();
        btnAceptacionProducto = new swing.Button();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(340, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 110, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(30, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(340, 750));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setToolTipText("");
        pnlMenu.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlMenu.setMinimumSize(new java.awt.Dimension(300, 800));
        pnlMenu.setPreferredSize(new java.awt.Dimension(300, 800));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        pnlMenu.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Logout.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlMenu.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 40, 40));

        btnInspeccionRecibo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnInspeccionRecibo.setText("INSPECCIÓN/RECIBO");
        btnInspeccionRecibo.setMaximumSize(new java.awt.Dimension(270, 36));
        btnInspeccionRecibo.setMinimumSize(new java.awt.Dimension(270, 36));
        btnInspeccionRecibo.setPreferredSize(new java.awt.Dimension(270, 36));
        btnInspeccionRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInspeccionReciboActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInspeccionRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        btnAceptacionProducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAceptacionProducto.setText("ACEPTACIÓN DEL PRODUCTO");
        btnAceptacionProducto.setMaximumSize(new java.awt.Dimension(270, 36));
        btnAceptacionProducto.setMinimumSize(new java.awt.Dimension(270, 36));
        btnAceptacionProducto.setPreferredSize(new java.awt.Dimension(270, 36));
        btnAceptacionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptacionProductoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAceptacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 290, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Proceso 3");
        jButton3.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton3.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton3.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 290, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("Proceso 4");
        jButton4.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton4.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton4.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 290, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("Proceso 5");
        jButton5.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton5.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton5.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 290, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("Proceso 6");
        jButton6.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton6.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton6.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setText("Proceso 7");
        jButton7.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton7.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton7.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 290, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setText("Proceso 8");
        jButton8.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton8.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton8.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 290, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("Proceso 9");
        jButton9.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton9.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton9.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 290, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("Proceso 10");
        jButton10.setMaximumSize(new java.awt.Dimension(270, 36));
        jButton10.setMinimumSize(new java.awt.Dimension(270, 36));
        jButton10.setPreferredSize(new java.awt.Dimension(270, 36));
        pnlMenu.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, -1));

        jScrollPane1.setViewportView(pnlMenu);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login login = new Login(); // Se crea una nueva instancia para regresar al apartado de inicion de Sesión
        login.setVisible(true); // Se muestra visible al usuario
        this.dispose(); // Se cierra la ventana actual y se liberan los recursos del sistema
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAceptacionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptacionProductoActionPerformed
        try {
            AceptacionProductoGUI apGUI = new AceptacionProductoGUI(usr); // Crea la Instancia de la clase
            apGUI.setVisible(true); // Se muestra visible al usuario
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptacionProductoActionPerformed

    private void btnInspeccionReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspeccionReciboActionPerformed
        try {
            InspeccionReciboGUI irGUI = new InspeccionReciboGUI(usr); // Crea la Instancia de la clase
            irGUI.setVisible(true); // Se muestra visible al usuario
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInspeccionReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptacionProducto;
    private javax.swing.JButton btnInspeccionRecibo;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
