package InspeccionRecibo;

import Modelos.InspeccionReciboM;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.GeneradorExcel;
import Servicios.InspeccionReciboServicio;
import Servicios.SQL;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class AgregarIrGUI extends javax.swing.JFrame {

    // Usuario y Conexión a la base de datos
    private Usuarios usuario;
    private Conexion conexion;

    // Servicios y Utilidades
    private InspeccionReciboServicio irs = new InspeccionReciboServicio();
    private GeneradorExcel excel = new GeneradorExcel();

    // Objeto para la manipulación de datos
    private final InspeccionReciboM inspeccionRecibo = new InspeccionReciboM();

    // Rutas de los archivos de la inspección
    private String rutaArchivoCertificado;
    private String rutaArchivoFactura;
    private String rutaArchivoHojaInstruccion;

    // Listas
    private List<String> proveedores = new ArrayList<>();

    public AgregarIrGUI() throws ClassNotFoundException {
        inicializarVentanaYComponentes();
    }

    public AgregarIrGUI(Usuarios usuario) throws ClassNotFoundException {
        try {
            inicializarVentanaYComponentes();
            cargarProveedores();
            generarCodigoHoja();
        } catch (SQLException ex) {
            Logger.getLogger(AgregarIrGUI.class.getName()).log(Level.SEVERE, null, ex);
            irs.manejarExcepcion("ERROR al inicializar AgregarIrGUI", ex);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        lblFechaFactura = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblNoPedido = new javax.swing.JLabel();
        lblCalibre = new javax.swing.JLabel();
        lblNoRollo = new javax.swing.JLabel();
        lblPzKg = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblHojaInstruccion = new javax.swing.JLabel();
        lblPresentacionLamina = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnGuardar = new swing.Button(new Color(121, 190, 255),new Color(10, 110, 255));
        lblNoFactura = new javax.swing.JLabel();
        dchFechaFactura = new com.toedter.calendar.JDateChooser();
        btnAgregarCertificado = new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        lblJCIcono = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        btnAgregarFactura = new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        txtNoRollo = new swing.TextField();
        txtPzKg = new swing.TextField();
        txtNoFactura = new swing.TextField();
        txtCalibre = new swing.TextField();
        txtNoPedido = new swing.TextField();
        txtNoHoja = new swing.TextField();
        txtNombreCertificado = new swing.TextField();
        txtNombreFactura = new swing.TextField();
        btnAgregarHojaInstruccion = new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        txtNombreHojaInstruccion = new swing.TextField();
        cbxPresentacionLamina = new swing.ComboBoxSuggestion();
        cbxProveedor = new swing.ComboBoxSuggestion();
        cbxEstatus = new swing.ComboBoxSuggestion();
        chkHoy = new swing.JCheckBoxCustom(new Color(20, 134, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(830, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaFactura.setForeground(new java.awt.Color(76, 109, 255));
        lblFechaFactura.setText("FECHA DE FACTURA:");
        jPanel1.add(lblFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        lblProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(76, 109, 255));
        lblProveedor.setText("PROVEEDOR:");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 100, -1));

        lblNoPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoPedido.setForeground(new java.awt.Color(76, 109, 255));
        lblNoPedido.setText("NO. PEDIDO:");
        jPanel1.add(lblNoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        lblCalibre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCalibre.setForeground(new java.awt.Color(76, 109, 255));
        lblCalibre.setText("CALIBRE:");
        jPanel1.add(lblCalibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, -1));

        lblNoRollo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoRollo.setForeground(new java.awt.Color(76, 109, 255));
        lblNoRollo.setText("NO. ROLLO:");
        jPanel1.add(lblNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, -1));

        lblPzKg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPzKg.setForeground(new java.awt.Color(76, 109, 255));
        lblPzKg.setText("PZ/Kg:");
        jPanel1.add(lblPzKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 210, -1));

        lblEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(76, 109, 255));
        lblEstatus.setText("ESTATUS:");
        jPanel1.add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, -1));

        lblHojaInstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHojaInstruccion.setForeground(new java.awt.Color(76, 109, 255));
        lblHojaInstruccion.setText("<html>NO. HOJA DE <br>INSTRUCCIONES: </html>");
        jPanel1.add(lblHojaInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        lblPresentacionLamina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPresentacionLamina.setForeground(new java.awt.Color(76, 109, 255));
        lblPresentacionLamina.setText("PRESENTACIÓN DE LAMINA:");
        jPanel1.add(lblPresentacionLamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, 60));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR  ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 160, 60));

        lblNoFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoFactura.setForeground(new java.awt.Color(76, 109, 255));
        lblNoFactura.setText("NO. FACTURA:");
        jPanel1.add(lblNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));
        jPanel1.add(dchFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));

        btnAgregarCertificado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarCertificado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCertificado.setText("Agregar Certificado");
        btnAgregarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCertificadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 40));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        lblJCIcono.setToolTipText("");
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        lblAgregar.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(10, 110, 255));
        lblAgregar.setText("AGREGAR");
        jPanel1.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 260, 50));

        btnAgregarFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarFactura.setText("Agregar Factura");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 383, 150, 40));
        jPanel1.add(txtNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 270, -1));
        jPanel1.add(txtPzKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 290, -1));
        jPanel1.add(txtNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 250, -1));
        jPanel1.add(txtCalibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 280, -1));
        jPanel1.add(txtNoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 250, -1));

        txtNoHoja.setEditable(false);
        jPanel1.add(txtNoHoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 210, -1));

        txtNombreCertificado.setEditable(false);
        jPanel1.add(txtNombreCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 180, 30));

        txtNombreFactura.setEditable(false);
        jPanel1.add(txtNombreFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 200, 30));

        btnAgregarHojaInstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarHojaInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarHojaInstruccion.setText("<html>Agregar Hoja <br>de Instrucción</html>");
        btnAgregarHojaInstruccion.setToolTipText("");
        btnAgregarHojaInstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHojaInstruccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarHojaInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, 40));

        txtNombreHojaInstruccion.setEditable(false);
        jPanel1.add(txtNombreHojaInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 190, 30));

        cbxPresentacionLamina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CINTA", "HOJA" }));
        jPanel1.add(cbxPresentacionLamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 140, -1));

        jPanel1.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 250, -1));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBERADA", "POR LIBERAR", "RECHAZADA", "CERTIFICADO INCOMPLETO", " " }));
        jPanel1.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 280, -1));

        chkHoy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        chkHoy.setForeground(new java.awt.Color(76, 109, 255));
        chkHoy.setText("HOY");
        chkHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHoyActionPerformed(evt);
            }
        });
        jPanel1.add(chkHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        seleccionarFactura();
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrarVentana();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtCalibre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el componente");
        } else {
            procesarArchivoXLS();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCertificadoActionPerformed
        seleccionarCertificado();
    }//GEN-LAST:event_btnAgregarCertificadoActionPerformed

    private void btnAgregarHojaInstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHojaInstruccionActionPerformed
        seleccionarHojaInstruccion();
    }//GEN-LAST:event_btnAgregarHojaInstruccionActionPerformed

    private void chkHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHoyActionPerformed
        if (chkHoy.isSelected()) {
            dchFechaFactura.setDate(new java.util.Date());
        } else {
            dchFechaFactura.setDate(null);
        }
    }//GEN-LAST:event_chkHoyActionPerformed

    public final void inicializarVentanaYComponentes() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);
        this.conexion = Conexion.getInstance();
    }

    private void cargarProveedores() throws SQLException {
        proveedores = irs.recuperarProveedores(conexion);
        proveedores.forEach(cbxProveedor::addItem);
    }

    private void generarCodigoHoja() throws SQLException {
        SQL sql = new SQL();
        int year = obtenerAnoActual();
        String codigoHoja = sql.getCodigoHoja(irs.SELECT_NO_HOJA_INSTRUCCION_SQL, year);
        String nuevoCodigo = sql.obtenerSiguiente(codigoHoja, String.valueOf(year));
        txtNoHoja.setText(nuevoCodigo);
    }

    private int obtenerAnoActual() {
        return Calendar.getInstance().get(Calendar.YEAR);
    }

    public void seleccionarCertificado() {
        rutaArchivoCertificado = seleccionarArchivoCertificado(txtNombreCertificado, rutaArchivoCertificado);
    }

    public void seleccionarFactura() {
        rutaArchivoFactura = seleccionarArchivoCertificado(txtNombreFactura, rutaArchivoFactura);
    }

    public void seleccionarHojaInstruccion() {
        rutaArchivoHojaInstruccion = seleccionarArchivoCertificado(txtNombreHojaInstruccion, rutaArchivoHojaInstruccion);
    }

    private void guardarDatos() {
        try {
            irs.agregar(conexion, inspeccionRecibo);
            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS.");
            cerrarVentana();
            irs.abrirInspeccionReciboGUI(usuario);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            irs.manejarExcepcion("Error al guardar la información: ", ex);
        }
    }

    private void cerrarVentana() {
        AgregarIrGUI.this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarIrGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AgregarIrGUI().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AgregarIrGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCertificado;
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnAgregarHojaInstruccion;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JComboBox<String> cbxPresentacionLamina;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JCheckBox chkHoy;
    private com.toedter.calendar.JDateChooser dchFechaFactura;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCalibre;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFechaFactura;
    private javax.swing.JLabel lblHojaInstruccion;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblNoPedido;
    private javax.swing.JLabel lblNoRollo;
    private javax.swing.JLabel lblPresentacionLamina;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblPzKg;
    private javax.swing.JTextField txtCalibre;
    private javax.swing.JTextField txtNoFactura;
    private javax.swing.JTextField txtNoHoja;
    private javax.swing.JTextField txtNoPedido;
    private javax.swing.JTextField txtNoRollo;
    private javax.swing.JTextField txtNombreCertificado;
    private javax.swing.JTextField txtNombreFactura;
    private javax.swing.JTextField txtNombreHojaInstruccion;
    private javax.swing.JTextField txtPzKg;
    // End of variables declaration//GEN-END:variables

    private void procesarArchivoXLS() {

        Date fechaSeleccionada = dchFechaFactura.getDate();

        String noHoja = txtNoHoja.getText().trim();
        String[] partes = noHoja.split("/");
        String numeroStr = partes[1];
        int numero = Integer.parseInt(numeroStr);

        numeroStr = String.valueOf(numero);

        String nomHJ = txtNombreHojaInstruccion.getText();
        String nomFactura = txtNombreFactura.getText();
        String nomCert = txtNombreCertificado.getText();

        String estatus = cbxEstatus.getSelectedItem().toString();
        String calibre = txtCalibre.getText().trim();
        String pLamina = cbxPresentacionLamina.getSelectedItem().toString();
        String proveedor = cbxProveedor.getSelectedItem().toString();
        String noFactura = txtNoFactura.getText().trim();
        String noPedido = txtNoPedido.getText().trim();
        String noRollo = txtNoRollo.getText().trim();
        String pzKg = txtPzKg.getText().trim();

        if (fechaSeleccionada == null) {
            try {
                File archivoSeleccionado = new File(rutaArchivoHojaInstruccion);
                XSSFWorkbook workbook;
                try (FileInputStream fis = new FileInputStream(archivoSeleccionado)) {
                    workbook = new XSSFWorkbook(fis);
                    Sheet hoja1 = workbook.getSheetAt(0); // Obtener la primera hoja del libro (índice 0)                    

                    excel.setDatosCeldas(hoja1, 5, 2, numeroStr); // No. de Hoja

                    excel.getDatosCeldas(hoja1, 13, 5);
                    excel.getDatosCeldas(hoja1, 13, 7);

                    DataFormatter formatter = new DataFormatter();
                    Cell celdaFechaFactura = hoja1.getRow(9).getCell(8); // Fecha Factura
                    String formatoFecha = formatter.formatCellValue(celdaFechaFactura);

                    inspeccionRecibo.setFechaFactura(formatoFecha);
                    inspeccionRecibo.setProveedor(excel.getDatosCeldas(hoja1, 9, 4)); // Proveedor
                    inspeccionRecibo.setNoFactura(excel.getDatosCeldas(hoja1, 9, 6)); // No. Factura
                    inspeccionRecibo.setNoPedido(excel.getDatosCeldas(hoja1, 13, 3)); // No. Pedido
                    inspeccionRecibo.setCalibre(calibre);
                    inspeccionRecibo.setpLamina(pLamina);
                    inspeccionRecibo.setNoRollo(excel.getDatosCeldas(hoja1, 13, 5)); // No Rollo
                    inspeccionRecibo.setPzKg(excel.getDatosCeldas(hoja1, 13, 7)); // No PZKG
                    inspeccionRecibo.setEstatus(estatus);
                    inspeccionRecibo.setNoHoja(noHoja);

                }

                try (FileOutputStream fos = new FileOutputStream(archivoSeleccionado)) { // Guardar los cambios en el archivo
                    workbook.write(fos);
                }

                try {

                    irs.cargarArchivo(rutaArchivoHojaInstruccion, inspeccionRecibo::setHojaIns);

                    if (irs.existeNoRollo(txtNoRollo.getText())) {
                        JOptionPane.showMessageDialog(this, "Rollo registrado previamente");
                    }
                    guardarDatos(); // Se guardan los datos

                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "El documento esta abierto o esta siendo utilizado por otro proceso");
                }

            } catch (IOException e) {
                Logger.getLogger(AgregarIrGUI.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
            // Se almacenan los datos capturados en las variable
            String fechaFactura = irs.formatearFecha(fechaSeleccionada); // Formatea la fecha y guárdala en una variable String

            // Si los campos no estan vacios
            if (!proveedor.isEmpty() || !noFactura.isEmpty() || !noPedido.isEmpty() || !calibre.isEmpty() || !pLamina.isEmpty() || !noRollo.isEmpty() || !pzKg.isEmpty() || !fechaFactura.isEmpty()) {
                irs.validarArchivos(rutaArchivoCertificado, rutaArchivoFactura, rutaArchivoHojaInstruccion, inspeccionRecibo);

                // Se guardan el resto de los atributos de la instancia
                inspeccionRecibo.setFechaFactura(fechaFactura);
                inspeccionRecibo.setProveedor(proveedor);
                inspeccionRecibo.setNoFactura(noFactura);
                inspeccionRecibo.setNoPedido(noPedido);
                inspeccionRecibo.setCalibre(calibre);
                inspeccionRecibo.setpLamina(pLamina);
                inspeccionRecibo.setNoRollo(noRollo);
                inspeccionRecibo.setPzKg(pzKg);
                inspeccionRecibo.setEstatus(estatus);
                inspeccionRecibo.setNoHoja(noHoja);
                inspeccionRecibo.setNombreHJ(nomHJ);
                inspeccionRecibo.setNombreFact(nomFactura);
                inspeccionRecibo.setNombreCert(nomCert);

                try {
                    if (irs.existeNoRollo(txtNoRollo.getText())) {
                        JOptionPane.showMessageDialog(this, "Rollo registrado previamente");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AgregarIrGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                guardarDatos(); // Se guardan los datos

            } else { // Si el calibre esta vacío se muestra el mensaje
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
            }
        }
    }

    public String seleccionarArchivoCertificado(JTextField textField, String rutaArchivo) {
        File archivoSeleccionado = irs.seleccionarArchivo(this);
        if (archivoSeleccionado != null) {
            String nombreArchivo = archivoSeleccionado.getName();
            rutaArchivo = archivoSeleccionado.getAbsolutePath();
            textField.setText(nombreArchivo);
        }
        return rutaArchivo;
    }
}
