package InspeccionRecibo;

import Modelos.InspeccionReciboM;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.InspeccionReciboServicio;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class ModificarIrGUI extends javax.swing.JFrame {

    // Usuario y Conexión a la base de datos
    private Usuarios usuario;
    private Connection conexion;

    // Objetos para manejar la información
    private InspeccionReciboM inspeccionRecibo;
    private InspeccionReciboM inspeccionReciboOriginal;

    // Variables para guardar las rutas de los archivos
    private String rutaArchivoFactura;
    private String rutaArchivoCertificado;
    private String rutaArchivoHojaInstruccion;

    // Servicios y Utilidades
    private InspeccionReciboServicio irs = new InspeccionReciboServicio();

    // Constructores
    public ModificarIrGUI() {
        inicializarVentanaYComponentes();
    }

    public ModificarIrGUI(InspeccionReciboM inspeccionRecibo, Usuarios usuario) throws ClassNotFoundException {
        this.usuario = usuario;
        this.inspeccionRecibo = inspeccionRecibo;
        inicializarVentanaYComponentes();
        cargarDatosEnComponentes();
        cargarProveedoresEnComboBox();
        establecerFechaFactura();
        this.inspeccionReciboOriginal = clonarInspeccionRecibo(inspeccionRecibo);
    }

    public ModificarIrGUI(InspeccionReciboM inspeccionRecibo, Usuarios usuario, String rutaArchivoHojaInstruccion) throws ClassNotFoundException {
        this(inspeccionRecibo, usuario);
        this.rutaArchivoHojaInstruccion = rutaArchivoHojaInstruccion;
        txtNombreHojaInstruccion.setText(this.rutaArchivoHojaInstruccion);
    }

    @Override
    public Image getIconImage() { // Método para cambiar el icono en la barra del titulo
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("jc/img/jc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNoHoja = new swing.TextField();
        lblProveedor = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblNoRollo = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblPzKg = new javax.swing.JLabel();
        btnAgregarFactura =  new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        txtNoPedido = new swing.TextField();
        lblNoPedido = new javax.swing.JLabel();
        lblFechaFactura = new javax.swing.JLabel();
        txtPzKg = new swing.TextField();
        txtNoRollo = new swing.TextField();
        lblNoFactura = new javax.swing.JLabel();
        lblCalibre = new javax.swing.JLabel();
        lblHojaInstruccion = new javax.swing.JLabel();
        txtCalibre = new swing.TextField();
        lblPresentacionLamina = new javax.swing.JLabel();
        btnGuardar = new swing.Button();
        txtNoFactura = new swing.TextField();
        lblJCIcono = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAgregarCertificado = new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        txtNombreCertificado = new swing.TextField();
        txtNombreFactura = new swing.TextField();
        btnAgregarHojaInstrucciones = new swing.Button(new Color(255, 214, 125),new Color(255, 200, 81));
        txtNombreHojaInstruccion = new swing.TextField();
        cbxPresentacionLamina = new swing.ComboBoxSuggestion();
        cbxProveedor = new swing.ComboBoxSuggestion();
        cbxEstatus = new swing.ComboBoxSuggestion();
        dchFechaFactura = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 576));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 576));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNoHoja.setEditable(false);
        jPanel1.add(txtNoHoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 210, -1));

        lblProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(76, 109, 255));
        lblProveedor.setText("PROVEEDOR:");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 100, -1));

        lblEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(76, 109, 255));
        lblEstatus.setText("ESTATUS:");
        jPanel1.add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 210, -1));

        lblNoRollo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoRollo.setForeground(new java.awt.Color(76, 109, 255));
        lblNoRollo.setText("NO. ROLLO:");
        jPanel1.add(lblNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 20));

        lblModificar.setBackground(new java.awt.Color(10, 110, 255));
        lblModificar.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(10, 110, 255));
        lblModificar.setText("MODIFICAR");
        lblModificar.setMaximumSize(new java.awt.Dimension(562, 25));
        lblModificar.setMinimumSize(new java.awt.Dimension(562, 25));
        jPanel1.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        lblPzKg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPzKg.setForeground(new java.awt.Color(76, 109, 255));
        lblPzKg.setText("PZ/Kg:");
        jPanel1.add(lblPzKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 210, -1));

        btnAgregarFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarFactura.setText("Subir Factura");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 40));
        jPanel1.add(txtNoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 250, -1));

        lblNoPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoPedido.setForeground(new java.awt.Color(76, 109, 255));
        lblNoPedido.setText("NO. PEDIDO:");
        jPanel1.add(lblNoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        lblFechaFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaFactura.setForeground(new java.awt.Color(76, 109, 255));
        lblFechaFactura.setText("FECHA DE FACTURA:");
        jPanel1.add(lblFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));
        jPanel1.add(txtPzKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 290, -1));
        jPanel1.add(txtNoRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 280, -1));

        lblNoFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoFactura.setForeground(new java.awt.Color(76, 109, 255));
        lblNoFactura.setText("NO. FACTURA:");
        jPanel1.add(lblNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        lblCalibre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCalibre.setForeground(new java.awt.Color(76, 109, 255));
        lblCalibre.setText("CALIBRE:");
        jPanel1.add(lblCalibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        lblHojaInstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHojaInstruccion.setForeground(new java.awt.Color(76, 109, 255));
        lblHojaInstruccion.setText("<html>NO. HOJA DE <br>INSTRUCCIONES: </html>");
        jPanel1.add(lblHojaInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));
        jPanel1.add(txtCalibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 290, -1));

        lblPresentacionLamina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPresentacionLamina.setForeground(new java.awt.Color(76, 109, 255));
        lblPresentacionLamina.setText("PRESENTACIÓN DE LAMINA:");
        jPanel1.add(lblPresentacionLamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 160, 60));
        jPanel1.add(txtNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 270, -1));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        lblJCIcono.setToolTipText("");
        jPanel1.add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, 60));

        btnAgregarCertificado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarCertificado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCertificado.setText("Subir Certificado");
        btnAgregarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCertificadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 40));

        txtNombreCertificado.setEditable(false);
        jPanel1.add(txtNombreCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 190, -1));

        txtNombreFactura.setEditable(false);
        jPanel1.add(txtNombreFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 200, -1));

        btnAgregarHojaInstrucciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarHojaInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarHojaInstrucciones.setText("<html>Subir Hoja de <br> Instrucciones</html>");
        btnAgregarHojaInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHojaInstruccionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarHojaInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 170, -1));

        txtNombreHojaInstruccion.setEditable(false);
        jPanel1.add(txtNombreHojaInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 200, -1));

        cbxPresentacionLamina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CINTA", "HOJA" }));
        jPanel1.add(cbxPresentacionLamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 140, -1));

        jPanel1.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 240, -1));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBERADA", "POR LIBERAR", "RECHAZADA", "CERTIFICADO INCOMPLETO" }));
        jPanel1.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 300, -1));
        jPanel1.add(dchFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrarVentana();
        irs.abrirInspeccionReciboGUI(usuario);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Date fechaSeleccionada = dchFechaFactura.getDate();
        String fechaFactura = irs.formatearFecha(fechaSeleccionada);

        String proveedor = irs.obtenerValorComboBox(cbxProveedor);
        String noFactura = irs.obtenerTexto(txtNoFactura);
        String noPedido = irs.obtenerTexto(txtNoPedido);
        String calibre = irs.obtenerTexto(txtCalibre);
        String presentacionLamina = irs.obtenerValorComboBox(cbxPresentacionLamina);
        String noRollo = irs.obtenerTexto(txtNoRollo);
        String pzKg = irs.obtenerTexto(txtPzKg);
        String estatus = irs.obtenerValorComboBox(cbxEstatus);
        String noHoja = irs.obtenerTexto(txtNoHoja);
        String nombreHI = irs.obtenerTexto(txtNombreHojaInstruccion);
        String nombreFact = irs.obtenerTexto(txtNombreFactura);
        String nombreCert = irs.obtenerTexto(txtNombreCertificado);

        if (camposCompletos(proveedor, noFactura, noPedido, calibre, presentacionLamina, noRollo, pzKg, estatus, fechaFactura)) {
            actualizarInspeccionRecibo(fechaFactura, proveedor, noFactura, noPedido, calibre, presentacionLamina, noRollo, pzKg, estatus, noHoja, nombreHI, nombreFact, nombreCert);
            cargarArchivos();
            modificarDatos();
        } else {
            JOptionPane.showMessageDialog(this, "Favor de completar todos los campos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        seleccionarFactura();
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    private void btnAgregarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCertificadoActionPerformed
        seleccionarCertificado();
    }//GEN-LAST:event_btnAgregarCertificadoActionPerformed

    private void btnAgregarHojaInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHojaInstruccionesActionPerformed
        seleccionarHojaInstruccion();
        String rutaAuxiliar = rutaArchivoHojaInstruccion;
        cerrarVentana();
        rutaArchivoHojaInstruccion = irs.abrirHojaInstruccionGUI2(usuario, rutaAuxiliar, inspeccionRecibo);
    }//GEN-LAST:event_btnAgregarHojaInstruccionesActionPerformed

    public String seleccionarArchivoCertificado(JTextField textField, String rutaArchivo) {
        File archivoSeleccionado = this.irs.seleccionarArchivo(this);
        if (archivoSeleccionado != null) {
            String nombreArchivo = archivoSeleccionado.getName();
            rutaArchivo = archivoSeleccionado.getAbsolutePath();
            textField.setText(nombreArchivo);
        }
        return rutaArchivo;
    }

    public void cerrarVentana() {
        ModificarIrGUI.this.dispose();
    }

    private void modificarDatos() {
        try {
            irs.modificar(conexion, inspeccionRecibo, inspeccionReciboOriginal);
            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS.");
            cerrarVentana();
            irs.abrirInspeccionReciboGUI(usuario);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarIrGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error al actualizar el registro: " + ex);
        }
    }

    public void seleccionarCertificado() {
        rutaArchivoCertificado = seleccionarArchivoCertificado(txtNombreCertificado, rutaArchivoCertificado);
    }

    public void seleccionarFactura() {
        rutaArchivoFactura = seleccionarArchivoCertificado(txtNombreFactura, rutaArchivoFactura);
    }

    public void seleccionarHojaInstruccion() {
        rutaArchivoHojaInstruccion = seleccionarArchivoCertificado(txtNombreHojaInstruccion, rutaArchivoHojaInstruccion);
    }

    private void inicializarVentanaYComponentes() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.conexion = Conexion.getInstance().getConnection();
    }

    private void cargarDatosEnComponentes() {
        txtNoFactura.setText(inspeccionRecibo.getNoFactura());
        txtNoPedido.setText(inspeccionRecibo.getNoPedido());
        txtCalibre.setText(inspeccionRecibo.getCalibre());
        txtNoRollo.setText(inspeccionRecibo.getNoRollo());
        txtPzKg.setText(inspeccionRecibo.getPzKg());
        txtNombreFactura.setText(inspeccionRecibo.getNombreFact());
        txtNombreCertificado.setText(inspeccionRecibo.getNombreCert());
        txtNombreHojaInstruccion.setText(inspeccionRecibo.getNombreHJ());
        txtNoHoja.setText(String.valueOf(inspeccionRecibo.getNoHoja()));

        cbxEstatus.setSelectedItem(inspeccionRecibo.getEstatus());
        cbxPresentacionLamina.setSelectedItem(inspeccionRecibo.getpLamina());
        cbxProveedor.setSelectedItem(inspeccionRecibo.getProveedor());
    }

    private void cargarProveedoresEnComboBox() {
        try {
            List<String> proveedores = irs.recuperarProveedores(conexion);
            proveedores.forEach(cbxProveedor::addItem);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarIrGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de proveedores: " + ex);
        }
    }

    private void establecerFechaFactura() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaFactura = dateFormat.parse(inspeccionRecibo.getFechaFactura());
            dchFechaFactura.setDate(fechaFactura);
        } catch (ParseException e) {
            Logger.getLogger(ModificarIrGUI.class.getName()).log(Level.WARNING, "Error al parsear la fecha de la factura", e);
        }
    }

    private InspeccionReciboM clonarInspeccionRecibo(InspeccionReciboM original) {
        return new InspeccionReciboM(
                original.getId(),
                original.getFechaFactura(),
                "", "", "",
                original.getCalibre(),
                "",
                original.getNoRollo(),
                original.getPzKg(),
                "", "",
                original.getFacturapdf(),
                original.getCertificadopdf(),
                original.getHojaIns(),
                original.getNombreHJ(),
                original.getNombreFact(),
                original.getNombreCert()
        );
    }

    public boolean camposCompletos(String... campos) {
        for (String campo : campos) {
            if (campo.isEmpty()) {
                return false;
            }
        }
        return true;
    }

    private void actualizarInspeccionRecibo(String fechaFactura, String proveedor, String noFactura, String noPedido, String calibre, String pLamina, String noRollo, String pzKg, String estatus, String noHoja, String nombreHJ, String nombreFact, String nombreCert) {
        inspeccionRecibo.setFechaFactura(fechaFactura);
        inspeccionRecibo.setProveedor(proveedor);
        inspeccionRecibo.setNoFactura(noFactura);
        inspeccionRecibo.setNoPedido(noPedido);
        inspeccionRecibo.setCalibre(calibre);
        inspeccionRecibo.setpLamina(pLamina);
        inspeccionRecibo.setNoRollo(noRollo);
        inspeccionRecibo.setPzKg(pzKg);
        inspeccionRecibo.setEstatus(estatus);
        inspeccionRecibo.setNoHoja(noHoja);
        inspeccionRecibo.setNombreHJ(nombreHJ);
        inspeccionRecibo.setNombreFact(nombreFact);
        inspeccionRecibo.setNombreCert(nombreCert);
    }

    private void cargarArchivos() {
        irs.cargarArchivo(rutaArchivoFactura, inspeccionRecibo::setFacturapdf);
        irs.cargarArchivo(rutaArchivoCertificado, inspeccionRecibo::setCertificadopdf);
        irs.cargarArchivo(rutaArchivoHojaInstruccion, inspeccionRecibo::setHojaIns);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarIrGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarIrGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCertificado;
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnAgregarHojaInstrucciones;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JComboBox<String> cbxPresentacionLamina;
    private javax.swing.JComboBox<String> cbxProveedor;
    private com.toedter.calendar.JDateChooser dchFechaFactura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalibre;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFechaFactura;
    private javax.swing.JLabel lblHojaInstruccion;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblNoPedido;
    private javax.swing.JLabel lblNoRollo;
    private javax.swing.JLabel lblPresentacionLamina;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblPzKg;
    private javax.swing.JTextField txtCalibre;
    private javax.swing.JTextField txtNoFactura;
    private javax.swing.JTextField txtNoHoja;
    private javax.swing.JTextField txtNoPedido;
    private javax.swing.JTextField txtNoRollo;
    private javax.swing.JTextField txtNombreCertificado;
    private javax.swing.JTextField txtNombreFactura;
    private javax.swing.JTextField txtNombreHojaInstruccion;
    private javax.swing.JTextField txtPzKg;
    // End of variables declaration//GEN-END:variables
}
